### ISSUE TITLE
Incorrect email on Meetup page

### ISSUE THREAD

**Issue by Gdewilde** [serverless/meetups#8]
<img width="416" alt="screenshot 2018-09-12 at 21 24 58" src="https://user-images.githubusercontent.com/1112129/45448353-69d8bf80-b6d2-11e8-9d2a-fa64b0046c4a.png">

The `host your own meetup` button links to rupak@serverless.com which doesn't exist.

**Comment by thomcrowe** [comment]
Thanks for the head's up, this has been updated.
